* Instructional Materials

These are various teaching materials that I used to teach computer science
students in an Austrian technical secondary school (aka HTL) for informatics
mainly in the subjects “Networks and Distributed Systems” and “Software
Development”.

You will find the following "courses":

** [[file:build/cpp_intro/][An introduction to C++]]

This slide deck is intended for teaching beginners in C++ who already have
programming skills.

** [[file:build/distsys][Networks and distributed systems]]

A fairly complete teaching aid that covers the curriculum of the
subject "Networks and Distributed Systems".

*** [[file:exercises/distsys][Excercises]]

As part of the curriculum you will find assignments for the first term of the
final year that trains the basics of building clients and servers. They serve as
preparation for the creation of more realistic systems as they are teached in
the second term.

** [[file:build/dotnet_intro/][A really short introduction to .NET Core]]

Just a short overview to .NET Core and the basics of C#.

** [[file:build/python_intro/][A gentle introduction to Python]]

This is a gentle introduction to Python for beginners of this particular
programming language.

***  [[file:exercises/python][Python Excercises]]

These exercises cover the first year of learning Python as it has been used in
the technical secondary school (HTL) for computer science. The book
[[https://www.amazon.de/Python-f%C3%BCr-Kids-mitp/dp/382668673X][Python für Kids (mitp für Kids)]] (Gregor Lingl, MITP, 4. überarbeitete
Auflage 2010 (20. Mai 2008)) serves as the basis for these exercises.

** [[file:build/securecomm.html][A quick primer to secure communication]]

A short presentation to secure communication for the end user.

** [[file:build/swdev/][Software Development]]

This covers the curriculum almost completely in a form that is as independent as
possible of specific programming languages and frameworks.

*** [[file:exercises/cpp][C++ Excercises]]

As part of the curriculum, here you will find assignments that are suitable for
programmers to get the necessary routine in C++ and at the same time to repeat
and consolidate many relevant programming concepts.

These assignments have been developed for the final year course in programming
and software development at a technical secondary school for computer
science.

** [[file:build/web_intro/][Webdevelopment for Beginners]]

Nothing fancy, just an old slide deck that covers the basics of
HTML, CSS, JavaScript, and the foundations of HTTP.

Please note the license.
