# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import greeter_pb2 as greeter__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.say_hello = channel.unary_unary(
        '/greeter.Greeter/say_hello',
        request_serializer=greeter__pb2.HelloRequest.SerializeToString,
        response_deserializer=greeter__pb2.HelloResponse.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def say_hello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'say_hello': grpc.unary_unary_rpc_method_handler(
          servicer.say_hello,
          request_deserializer=greeter__pb2.HelloRequest.FromString,
          response_serializer=greeter__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'greeter.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
